<?php

use App\Modules\KatawaParser\v2\Modules\Dto\PositionDto;

return [

    /** Список всех персонажей, [ character_name => 'Описание' ] */
    'characters' => [
        'hi' => 'Хисао',
        'mk' => 'Мики',
        'har' => 'Хару',
        'suz' => 'Сузу',
        'yuk' => 'Юкио',
        'yu' => 'Юко',
        'ke' => 'Кендзи',
        'jun' => 'Папа',
        'mu' => 'Муто',
        'mot' => 'Мама Сузу',
        'dad' => 'Папа Сузу',
        'tsu' => 'Цубаса',
        'yam' => 'Ямада',
        'shi' => 'Сидзунэ',

        // Для совместимости
        'hisao_blank ' => 'hisao_blank ',
        'hisao_erm' => 'hisao_erm',
        'hisao_erm_u' => 'hisao_erm_u',
        'hisao_talk_big' => 'hisao_talk_big',
        'hisao_talk_big_u' => 'hisao_talk_big_u',
        'hisao_smile' => 'hisao_smile',
        'hisao_smile_u' => 'hisao_smile_u',
        'hisao_wtf' => 'hisao_wtf',
        'hisao_wtf_u' => 'hisao_wtf_u',
        'hisao_biggrin' => 'hisao_biggrin',
        'hisao_biggrin_u' => 'hisao_biggrin_u',
        'hisao_disappoint' => 'hisao_disappoint',
        'hisao_disappoint_u' => 'hisao_disappoint_u',
        'hisao_frown' => 'hisao_frown',
        'hisao_frown_u' => 'hisao_frown_u',
        'hisao_heh' => 'hisao_heh',
        'hisao_heh_u' => 'hisao_heh_u',
        'hisao_smile_teeth' => 'hisao_smile_teeth',
        'hisao_smile_teeth_u' => 'hisao_smile_teeth_u',
        'hisao_talk_small' => 'hisao_talk_small',
        'hisao_talk_small_u' => 'hisao_talk_small_u',
        'hisao_hmpf' => 'hisao_hmpf',
        'hisao_hmpf_u' => 'hisao_hmpf_u',
        'hisao_closed' => 'hisao_closed',
        'hisao_closed_u' => 'hisao_closed_u',
        'hisao_declare' => 'hisao_declare',
        'hisao_declare_u' => 'hisao_declare_u',
        'hisao_blush' => 'hisao_blush',
        'hisao_blush_u' => 'hisao_blush_u',
        'hisao_beach_blush' => 'hisao_beach_blush',
        'hisao_beach_frown' => 'hisao_beach_frown',
        'hisao_beach_smile' => 'hisao_beach_smile',
        'hisao_beach_erm' => 'hisao_beach_erm',
        'hisao_beach_disappoint' => 'hisao_beach_disappoint',
        'hisao_beach_talk' => 'hisao_beach_talk',
        'hisao_beach_grin' => 'hisao_beach_grin',
        'hisao_beach_declare' => 'hisao_beach_declare',
        'hisao_topless' => 'hisao_topless',
        'hisao_pale' => 'hisao_pale',
        'hisao_wtf_close' => 'hisao_wtf_close',
        'hisao_wtf_close_u' => 'hisao_wtf_close_u',
        'hisao_erm_close' => 'hisao_erm_close',
        'hisao_erm_close_u' => 'hisao_erm_close_u',
        'hisao_smile_close' => 'hisao_smile_close',
        'hisao_smile_close_u' => 'hisao_smile_close_u',
        'hisao_topless_smile' => 'hisao_topless_smile',
        'rin' => 'rin',
        'haru_annoyed' => 'haru_annoyed',
        'haru_basic' => 'haru_basic',
        'haru_sad' => 'haru_sad',
        'haru_serious' => 'haru_serious',
        'haru_smile' => 'haru_smile',
        'haru_yo' => 'haru_yo',
        'suzu_angry' => 'suzu_angry',
        'suzu_angry_d' => 'suzu_angry_d',
        'suzu_concerned' => 'suzu_concerned',
        'suzu_concerned_d' => 'suzu_concerned_d',
        'suzu_embarrassed' => 'suzu_embarrassed',
        'suzu_embarrassed_d' => 'suzu_embarrassed_d',
        'suzu_grin' => 'suzu_grin',
        'suzu_grin_d' => 'suzu_grin_d',
        'suzu_happy' => 'suzu_happy',
        'suzu_happy_d' => 'suzu_happy_d',
        'suzu_invis' => 'suzu_invis',
        'suzu_normal' => 'suzu_normal',
        'suzu_normal_d' => 'suzu_normal_d',
        'suzu_side' => 'suzu_side',
        'suzu_smile' => 'suzu_smile',
        'suzu_smile_d' => 'suzu_smile_d',
        'suzu_speak' => 'suzu_speak',
        'suzu_speak_d' => 'suzu_speak_d',
        'suzu_surprised' => 'suzu_surprised',
        'suzu_surprised_d' => 'suzu_surprised_d',
        'suzu_veryangry' => 'suzu_veryangry',
        'suzu_veryangry_d' => 'suzu_veryangry_d',
        'suzu_unhappy' => 'suzu_unhappy',
        'suzu_unhappy_d' => 'suzu_unhappy_d',
        'suzu_sleepy' => 'suzu_sleepy',
        'suzu_sleepy_d' => 'suzu_sleepy_d',
        'suzu_asleep' => 'suzu_asleep',
        'suzu_asleep_d' => 'suzu_asleep_d',
        'suzu_veryembarrassed' => 'suzu_veryembarrassed',
        'suzu_veryembarrassed_d' => 'suzu_veryembarrassed_d',
        'suzu_beach_normal' => 'suzu_beach_normal',
        'suzu_beach_annoyed' => 'suzu_beach_annoyed',
        'suzu_beach_angry' => 'suzu_beach_angry',
        'suzu_beach_smile' => 'suzu_beach_smile',
        'suzu_beach_small_em' => 'suzu_beach_small_em',
        'suzu_beach_sad' => 'suzu_beach_sad',
        'suzu_beach_surprised' => 'suzu_beach_surprised',
        'suzu_cry' => 'suzu_cry',
        'suzu_cry_d' => 'suzu_cry_d',
        'suzu_cry_smile' => 'suzu_cry_smile',
        'suzu_cry_smile_d' => 'suzu_cry_smile_d',
        'suzu_despair' => 'suzu_despair',
        'suzu_despair_d' => 'suzu_despair_d',
        'suzu_neutral' => 'suzu_neutral',
        'suzu_neutral_d' => 'suzu_neutral_d',
        'suzu_glare' => 'suzu_glare',
        'suzu_glare_d' => 'suzu_glare_d',
        'yukio_angry' => 'yukio_angry',
        'yukio_blush' => 'yukio_blush',
        'yukio_eeh' => 'yukio_eeh',
        'yukio_huh' => 'yukio_huh',
        'yukio_notimpressed' => 'yukio_notimpressed',
        'yukio_smile' => 'yukio_smile',
        'yukio_punched' => 'yukio_punched',
        'yukio_punched_defiant' => 'yukio_punched_defiant',
        'yukio_punched_angry' => 'yukio_punched_angry',
        'yuukoshang_happy_down' => 'yuukoshang_happy_down',
        'yuukoshang_happy_up' => 'yuukoshang_happy_up',
        'yuuko_neurotic_up' => 'yuuko_neurotic_up',
        'yuuko_cry_up' => 'yuuko_cry_up',
        'yuuko_worried_up' => 'yuuko_worried_up',
        'yuuko_neutral_down' => 'yuuko_neutral_down',
        'kenji_neutral' => 'kenji_neutral',
        'kenji_tsun' => 'kenji_tsun',
        'kenji_happy' => 'kenji_happy',
        'kimono_normal' => 'kimono_normal',
        'kimono_unhappy' => 'kimono_unhappy',
        'kimono_embarrassed' => 'kimono_embarrassed',
        'kimono_grin' => 'kimono_grin',
        'kimono_happy' => 'kimono_happy',
        'tsu_tooth_smile' => 'tsu_tooth_smile',
        'tsu_annoyed' => 'tsu_annoyed',
        'tsu_smile' => 'tsu_smile',
        'tsu_tongue' => 'tsu_tongue',
        'tsu_deadpan' => 'tsu_deadpan',
        'tsu_ooh' => 'tsu_ooh',
        'tsu_sad' => 'tsu_sad',
        'tsu_question' => 'tsu_question',
        'tsu_hmm' => 'tsu_hmm',
        'tsu_erm' => 'tsu_erm',
        'tsu_dumps' => 'tsu_dumps',
        'tsu_beach_deadpan' => 'tsu_beach_deadpan',
        'tsu_beach_erm' => 'tsu_beach_erm',
        'tsu_beach_closed' => 'tsu_beach_closed',
        'tsu_beach_tooth_smile' => 'tsu_beach_tooth_smile',
        'mother_normal' => 'mother_normal',
        'mother_soften' => 'mother_soften',
        'mother_angry' => 'mother_angry',
        'mother_yell' => 'mother_yell',
        'mother_tight' => 'mother_tight',
        'mother_murder' => 'mother_murder',
        'mother_closed' => 'mother_closed',
        'mother_smile' => 'mother_smile',
        'miyu_happy' => 'miyu_happy',
        'miyu_normal' => 'miyu_normal',
        'AGirl' => 'AGirl',
        'phone' => 'phone',
        'junko_question' => 'junko_question',
        'junko_smile' => 'junko_smile',
        'junko_frown' => 'junko_frown',
        'junko_grin' => 'junko_grin',
        'junko_embarrassed' => 'junko_embarrassed',
        'shizu_basic_normal2' => 'shizu_basic_normal2',
        'shizu_behind_blank' => 'shizu_behind_blank',
        'shizu_basic_angry' => 'shizu_basic_angry',
        'shizu_cross_angry' => 'shizu_cross_angry',
        'shizu_behind_frown' => 'shizu_behind_frown',
        'dad_smile' => 'dad_smile',
        'dad_smirk' => 'dad_smirk',
        'dad_laugh' => 'dad_laugh',
        'dad_talk' => 'dad_talk',
        'dad_grump' => 'dad_grump',
        'dad_normal' => 'dad_normal',
        'dad_frown' => 'dad_frown',
        'dad_unhappy' => 'dad_unhappy',
        'dad_smile_close' => 'dad_smile_close',
        'muto_irritated' => 'muto_irritated',
        'muto_normal' => 'muto_normal',
        'muto_smile' => 'muto_smile',
        'aoi_smile' => 'aoi_smile',
        'aoi_surprised' => 'aoi_surprised',
        'saki' => 'saki',
        'saki_frown' => 'saki_frown',
        'haru_conehead' => 'haru_conehead',
        'suzu_angry_lift' => 'suzu_angry_lift',
        'suzu_speak_close' => 'suzu_speak_close',
        'suzu_speak_close_d' => 'suzu_speak_close_d',
        'kimono_happy_close' => 'kimono_happy_close',
        'suzu_veryembarrassed_close' => 'suzu_veryembarrassed_close',
        'suzu_veryembarrassed_close_d' => 'suzu_veryembarrassed_close_d',
        'suzu_smile_close' => 'suzu_smile_close',
        'suzu_smile_close_d' => 'suzu_smile_close_d',
        'suzu_father_happy' => 'suzu_father_happy',
        'suzu_father_unhappy' => 'suzu_father_unhappy',
        'suzu_father_normal' => 'suzu_father_normal',
        'suzu_father_shock' => 'suzu_father_shock',
    ],

    /**
     * Если персонажи заданы видом 'hisao_smile_u' => '...' то нужно прописывать путь foreground/hisao_smile_u/...
     * Чтобы этого избежать можно ниже перечислить сокращения вида 'hisao_' => 'hisao'
     * Тогда hisao_smile_u превратиться в hisao и файл с изображением будет доступен по пути foreground/hisao/...
     * Проверяет на совпадение в начале строки
     */
    'replace_long_characters' => [
        'hisao_' => 'hisao',
        'haru_' => 'haru',
        'suzu_' => 'suzu',
        'kimono_' => 'kimono',
        'saki_' => 'saki',
        'aoi_' => 'aoi',
        'muto_' => 'muto',

        'dad_' => 'dad',
        'shizu_' => 'shizu',
        'junko_' => 'junko',
        'miyu_' => 'miyu',
        'mother_' => 'mother',
        'tsu_' => 'tsu',
        'kenji_' => 'kenji',
        'yuuko_' => 'yuuko',
        'yuukoshang_' => 'yuukoshang',
        'yukio_' => 'yukio',

        'kid_' => 'kid',


        /**
         * Пустышки
         */
        'rin' => 'rin',
        'saki' => 'saki',
        'AGirl' => 'AGirl',
    ],

    /** Путь к игре */
    'game_path' => public_path('games/sc'),

    /**
     * Команды и обработчики для них
     */
    'commands' => [
        'default' => \App\Modules\KatawaParser\v2\Modules\Commands\DefaultCommand::class,
        'note' => \App\Modules\KatawaParser\v2\Modules\Commands\NoteCommand::class,
        'quote' => \App\Modules\KatawaParser\v2\Modules\Commands\QuoteCommand::class,
        'label' => \App\Modules\KatawaParser\v2\Modules\Commands\LabelCommand::class,
        'hide' => \App\Modules\KatawaParser\v2\Modules\Commands\HideCommand::class,
        'scene' => \App\Modules\KatawaParser\v2\Modules\Commands\SceneCommand::class,
        'with' => \App\Modules\KatawaParser\v2\Modules\Commands\WithCommand::class,
        'play' => \App\Modules\KatawaParser\v2\Modules\Commands\PlayCommand::class,
        'say' => \App\Modules\KatawaParser\v2\Modules\Commands\SayCommand::class,
        'stop' => \App\Modules\KatawaParser\v2\Modules\Commands\StopCommand::class,
        'emit' => \App\Modules\KatawaParser\v2\Modules\Commands\EmitCommand::class,
        'show' => \App\Modules\KatawaParser\v2\Modules\Commands\ShowCommand::class,

        'window' => \App\Modules\KatawaParser\v2\Modules\Commands\WindowCommand::class,
    ],

    /**
     * Для замены персонажей вида show phone
     *  В итоге будет img phone "vfx/mobile-sprite.png"
     *  параметр dissolve добавляет эффект появление длительностью 1 сек
     */
    'replace_characters_path' => [
        'lillyprop' => [
            'path' => 'vfx/prop_lilly_back_cane.png',
            'dissolve' => false
        ],
        'chessboard' => [
            'path' => 'vfx/chessboard.png',
            'dissolve' => true
        ],
        'mobile' => [
            'path' => 'vfx/mobile-sprite.png',
            'dissolve' => true
        ],
        'phone' => [
            'path' => 'vfx/mobile-sprite.png',
            'dissolve' => true
        ],
        'musicbox' => [
            'path' => 'vfx/musicbox_closed.png',
            'dissolve' => true
        ],
        'hanako_door_base' => [
            'path' => 'vfx/hanako_door_base.jpg',
            'dissolve' => true
        ],
        'hanako_door_door' => [
            'path' => 'vfx/hanako_door_door.jpg',
            'dissolve' => true
        ],
        'letter_insert' => [
            'path' => 'vfx/letter_insert.png',
            'dissolve' => true
        ],
    ],

    /** Замена персонажей */
    'replace_characters' => [
        'evbg' => 'lilly',
    ],

    /** Персонажи которые общаются жестами */
    'sign_characters' => [

    ],

    /** Удаляет постфиксы с bg */
    'replace_bg_postfix' => [

    ],

    /** Музыка */
    'music_replace' => [
        "music_miki" => "Carefree_Days.ogg",
        "music_daily" => "Daylight.ogg",
        "music_soothing" => "Air_original.ogg",
        "music_best_shot" => "Carefree_Days.ogg",
        "music_grease" => "Carefree_Days.ogg",
        "music_running" => "Hokabi.ogg",
        "music_jazz" => "Red_Velvet.ogg",
        "music_tragic" => "Cold_Iron.ogg",
        "music_pearly" => "Stride.ogg",
        "music_night" => "Nocturne.ogg",
        "music_moonlight" => "Breathlessly.ogg",
        "music_innocence" => "Innocence.ogg",
        "music_credits" => "Romance_in_Andante.ogg",
        "music_drama" => "Moment_of_Decision.ogg",
        "music_Out_of_the_Loop" => "Out_of_the_Loop.ogg",
        "music_lullaby" => "Lullaby_of_Open_Eyes.ogg",
        "music_ease" => "Ease.ogg",
        "music_timeskip" => "Passing_of_Time.ogg",
        "music_tranquil" => "Afternoon.ogg",
        "music_fripperies" => "Fripperies.ogg",
        "music_tension" => "High_Tension.ogg",
        "music_normal" => "School_Days.ogg",
        "music_suzu" => "Autumn.ogg",
        "music_everyday_fantasy" => "Everyday_Fantasy.ogg",
        "music_caged_heart" => "Caged_Heart.ogg",
        "music_raindrops" => "Raindrops_and_Puddles.ogg",
        "music_painful" => "Painful_History.ogg",
        "music_ah" => "Ah_Eh_I_Oh_You.ogg",
        "music_friendship" => "Friendship.ogg",
        "music_heart" => "Letting_my_Heart_Speak.ogg",
        "music_shadow" => "Shadow_of_the_Truth.ogg",
        "music_to_become_one" => "To_Become_One.ogg",
        "music_aria" => "Aria_de_l'Etoile.ogg",
        "music_comfort" => "Comfort.ogg",
        "music_generic_happy" => "Generic_Happy.ogg",

    ],

    /** SFX звуки */
    'sfx_replace' => [
        "sfx_can_clatter" => "can_clatter",
        "sfx_park" => "parkambience",
        "sfx_crowd_indoors" => "crowd_indoors",
        "sfx_normalbell" => "carillon",
        "sfx_crowd_outdoors" => "crowd_outdoors",
        "sfx_storebell" => "storebell",
        "sfx_blop" => "blop",
        "sfx_fireworks" => "fireworks",
        "sfx_running" => "running",
        "sfx_birdstakeoff" => "birdstakeoff",
        "sfx_traffic" => "traffic",
        "sfx_pillow" => "pillow",
        "sfx_broken_plate" => "broken_plate",
        "sfx_sitting" => "sitting",
        "sfx_dooropen" => "dooropen",
        "sfx_impact" => "wumph",
        "sfx_splash" => "splash",
        "sfx_void" => "void.mp3",
        "sfx_doorclose" => "doorclose",
        "sfx_rain" => "rain",
        "sfx_doorknock_soft" => "doorknock2",
        "sfx_doorknock" => "doorknock",
        "sfx_shower" => "shower",
        "sfx_alarmclock" => "alarm",
        "sfx_switch" => "switch",
        "sfx_hammer" => "hammer",
        "sfx_rustling" => "rustling",
        "sfx_whiteout" => "whiteout",
        "sfx_car_driving" => "car_driving",
        "sfx_cycling" => "cycling",
        "sfx_can" => "can",
        "sfx_tray_rattling" => "tray_rattling",
        "sfx_bat_hit" => "bat_hit",
        "sfx_kick_machine" => "kick_machine",
        "sfx_snap" => "snap",
        "sfx_doorslam" => "doorslam",
        "sfx_tcard" => "tcard",
        "sfx_rumble" => "rumble",
        "sfx_cicadas" => "cicadas",
        "sfx_cellphone" => "cellphone",
        "sfx_cutlery" => "cutlery",
        "sfx_car_drive_off" => "car_drive_off",
        "sfx_car_door" => "car_door",
        "sfx_beach" => "beach",
        "sfx_photo" => "shutterfilm",
        "sfx_kei_arrive" => "kei_arrive",
        "sfx_clap" => "clap",
        "sfx_pothole" => "pothole",
        "sfx_sliding_door" => "sliding_door",
        "sfx_creaking_door" => "creaking_door",
        "sfx_wood_floor" => "wood_floor",
        "sfx_footsteps_hard" => "footsteps_hard",
        "sfx_brook" => "brook",
        "sfx_crickets" => "crickets",
        "sfx_twig_snap" => "twig_snap",
        "sfx_forest" => "forest",
    ],

    /** Виды позиций */
    'positions' => [
        'center' => PositionDto::make('center', 'center'),

        'right' => PositionDto::make('right', 'center'),
        'tworight' => PositionDto::make('right', 'center'),

        'left' => PositionDto::make('left', 'center'),
        'twoleft' => PositionDto::make('left', 'center'),

        // GG
        'oneleft' => PositionDto::make('left', 'center'),
        'oneright' => PositionDto::make('right', 'center'),
        'twoleftsit' => PositionDto::make('left-in', '15%'),
        'tworightsit' => PositionDto::make('right-in', '15%'),
        'leftsit' => PositionDto::make('left-in', '15%'),
        'rightsit' => PositionDto::make('right-in', '15%'),
        'centersit' => PositionDto::make('center', '15%'),
        'centersit2' => PositionDto::make('center', '07%'),
        'centersitlow' => PositionDto::make('center', '25%'),
        'twoleftsitlow' => PositionDto::make('left-in', '25%'),
        'oneleftsitlow' => PositionDto::make('left', '25%'),
        'onerightsitlow' => PositionDto::make('right', '25%'),
        'tworightsitlow' => PositionDto::make('right-in', '25%'),

        'closeleft' => PositionDto::make('left', 'center'),
        'closeright' => PositionDto::make('right', 'center'),
        'closeleft2' => PositionDto::make('0%', 'center'),

        'rightedge' => PositionDto::make('right-in', 'center'),
        'leftoff' => PositionDto::make('left-in', 'center'),
        'centeroff' => PositionDto::make('center', 'center'),

        'twoleftoff' => PositionDto::make('20%', 'center'),
        'tworightoff' => PositionDto::make('68%', 'center'),
        'twocenteroff' => PositionDto::make('30%', 'center'),
        'twocenteroff2' => PositionDto::make('50%', 'center'),
        'twocenteroff3' => PositionDto::make('70%', 'center'),

        'tworightstagger' => PositionDto::make('right', 'center'),

        'leftdoor' => PositionDto::make('10%', 'center'),
        'leftdooropen' => PositionDto::make('-10%', 'center'),
        'rightwallopen' => PositionDto::make('85%', 'center'),
        'roomopen' => PositionDto::make('45%', 'center'),

        'leftoffsit' => PositionDto::make('left-in', '15%'),
        'rightedgesit' => PositionDto::make('right-in', '15%'),

        'oneleftsit' => PositionDto::make('left', '15%'),
        'onerightsit' => PositionDto::make('right', '15%'),

        'leftsitlow' => PositionDto::make('left-in', '25%'),
        'rightsitlow' => PositionDto::make('right-in', '25%'),

        'rightedgetsu' => PositionDto::make('70%', 'center'),
        'tworighttsu' => PositionDto::make('70%', 'center'),
        'leftoffmiyu' => PositionDto::make('1%', 'center'),

    ]
];
