<?php

return [
    'music_tranquil' => 'Afternoon.ogg',
    'music_nurse' => 'Ah_Eh_I_Oh_You.ogg',
    'music_soothing' => 'Air_Guitar.ogg',
    'music_twinkle' => 'Aria_de_lEtoile.ogg',
    'music_moonlight' => 'Breathlessly.ogg',
    'music_rain' => 'Caged_Heart.ogg',
    'music_tragic' => 'Cold_Iron.ogg',
    'music_comfort' => 'Comfort.ogg',
    'music_lilly' => 'Concord.ogg',
    'music_daily' => 'Daylight.ogg',
    'music_ease' => 'Ease.ogg',
    'music_another' => 'Everyday_Fantasy.ogg',
    'music_friendship' => 'Friendship.ogg',
    'music_happiness' => 'Fripperies.ogg',
    'music_comedy' => 'Generic_Happy_Music.ogg',
    'music_tension' => 'High_Tension.ogg',
    'music_running' => 'Hokabi.ogg',
    'music_innocence' => 'Innocence.ogg',
    'music_heart' => 'Letting_my_Heart_Speak.ogg',
    'music_serene' => 'Lullaby_of_Open_Eyes.ogg',
    'music_drama' => 'Moment_of_Decision.ogg',
    'music_night' => 'Nocturne.ogg',
    'music_kenji' => 'Out_of_the_Loop.ogg',
    'music_hanako' => 'Painful_History.ogg',
    'music_rin' => 'Parity.ogg',
    'music_timeskip' => 'Passing_of_Time.ogg',
    'music_dreamy' => 'Raindrops_and_Puddles.ogg',
    'music_jazz' => 'Red_Velvet.ogg',
    'music_romance' => 'Romance_in_Andante_II.ogg',
    'music_credits' => 'Romance_in_Andante.ogg',
    'music_musicbox' => 'Sarabande_from_BWV1010,_Musicbox.ogg',
    'music_normal' => 'School_Days.ogg',
    'music_sadness' => 'Shadow_of_the_Truth.ogg',
    'music_emi' => 'Standing_Tall.ogg',
    'music_pearly' => 'Stride.ogg',
    'music_shizune' => 'The_Student_Council.ogg',
    'music_one' => 'To_Become_One.ogg',
    'music_menus' => 'Wiosna.ogg',

    'music_chance' => 'Giving_Life_a_Chance.ogg',
    'music_rika' => 'Always_Strong.ogg',
    'music_saki' => 'Blossoming_Happiness_Theory.ogg',
    'music_teamV' => 'V_Means_Agony.ogg',
    'music_class24' => 'Vivisection.ogg',
    'music_box' => 'Whats_in_the_Box.ogg',
    'music_act_intro' => 'Life_Expectancy.ogg',

    'music_gentle' => 'Gentle_Mystique.ogg',
    'music_cellosolo' => 'BVW1010_Sarabande.ogg',

    /*
     * "bgm/Comfort.ogg" => "Comfort.ogg"
     */
    'bgm/' => '',

    'rutrip' => 'A_Trip_to_Russia',
    'soothing2' => 'Air_Piano',
    'bad_news' => 'Another_Bad_News',
    'backtovenus' => 'Back_to_Venus',
    'bedtime' => 'Bedtime_Story',
    'bimbam' => 'Bim_Bam_Smash',
    'butterfly' => 'Butterfly_with_Broken_Wings',
    'calmnight' => 'Calm_Night',
    'care' => 'Carefree_Days',
    'cfo' => 'Cold_Freezing_Out',
    'coma' => 'Coma',
    'credits_venus' => 'Credits_Music',
    'crew' => 'Crew',
    'dead_cities' => 'Dead_Cities',
    'decades' => 'Decades',
    'dejection' => 'Dejection',
    'departure' => 'Departure',
    'discovery' => 'Discovery',
    'dullness' => 'Everyday_Dullness',
    'gena' => 'Gena',
    'heat' => 'Heat',
    'inferiority' => 'Inferiority',
    'kodawari' => 'Kodawari',
    'last_breath' => 'Last_Breath',
    'leopold' => 'Leopold',
    'act1_intro' => 'Life_Expectancy',
    'lolo' => 'Lolo',
    'mental' => 'Mental_Trauma',
    'monks' => 'Metallic_Monks',
    'missing_you' => 'Missing_You',
    'oldhotel' => 'Old_Hotel',
    'planet' => 'Planet',
    'prologue' => 'Prologue_Music',
    'radwind1' => 'Radwind_Pt1',
    'radwind2' => 'Radwind_Pt2',
    'relevation' => 'Relevation',
    'routine' => 'Routine',
    'venus' => 'Singing_Planets',
    'smile' => 'Smile',
    'sonya_guitar' => 'Sonya_Tries_to_Play_on_Guitar',
    'web_amb' => 'Web_Amb',
    'wound' => 'Wound_of_Heart',
];
