<?php

namespace App\Modules\KatawaParser\v2\Modules\GameModel;

use App\Modules\KatawaParser\v2\KatawaCore;
use App\Modules\KatawaParser\v2\Modules\Configs\Config;
use App\Modules\KatawaParser\v2\Modules\Helpers\KatawaHelper;
use App\Modules\KatawaParser\v2\Modules\Tools\Tools;

class CharacterSayModel extends Model
{
    public string $character;
    public string $text;

    public function parse(): CharacterSayModel
    {
        $this->character = $this->line->get(KatawaCore::ARG_COMMAND);
        $this->character = $this->replaceCharacter($this->character);

        $line = clone $this->line;
        $line->forget(KatawaCore::ARG_COMMAND);

        $this->text = $line->implode(self::DELIMITER);

        if ($this->text && $this->text[0] === '|') {
            $this->text = substr($this->text, 1);
        }

        if (in_array($this->character, Config::getInstance()->getConfigValue('sign_characters'), true)) {
            $this->text = '[ ' . $line->implode(self::DELIMITER) . ' ]';
        }

        $this->text = KatawaHelper::replaceCharactersFromMessage($this->text);

        return parent::parse(); // TODO: Change the autogenerated stub
    }

    public function replaceCharacter(string $character) : string {

        foreach (Config::getInstance()->getConfigValue('replace_characters') as $key => $value) {
            if ($key === $character) {
                return $value;
            }
        }

        return $character;
    }

    public function compile(): string
    {
        $output = '[' . '$' . $this->character . '] ';
        $output .= Tools::quoted($this->text);

        return $output;
    }
}
