<?php

namespace Modules\KatawaCore\v2\Modules\GameModel;

use Modules\KatawaCore\v2\KatawaCore;
use Modules\KatawaCore\v2\Modules\Helpers\KatawaHelper;
use Str;

class NoteModel extends Model
{
    public const COMMAND = 'note';

    public string $text;

    public bool $html = false;

    public string $blockStart = '<span style=\'font-size: 250%;\'>\n\n';

    public string $blockEnd = '</span>';

    public function parse(): NoteModel
    {
        $line = clone $this->line;
        $line->forget(KatawaCore::ARG_COMMAND);

        $this->text = $line->implode(self::DELIMITER);
        $this->text = KatawaHelper::replaceCharactersFromMessage($this->text);

        return parent::parse(); // TODO: Change the autogenerated stub
    }

    public function compile(): string
    {
        if ($this->html) {
            return self::COMMAND.' + '.$this->blockStart.$this->text.$this->blockEnd;
        }

        if ($this->text === 'clear') {
            return self::COMMAND.' \n\n';
        }

        if ( Str::contains($this->text, 'dissolve', true)) {
            return self::COMMAND.' \n';
        }

        return self::COMMAND.' + '.$this->text;
    }

    public function setHtml(bool $html = true): NoteModel
    {
        $this->html = $html;

        return $this;
    }
}
