<?php

namespace App\Modules\KatawaParser\v2\Modules\GameModel;

use App\Modules\KatawaParser\v2\KatawaCore;
use App\Modules\KatawaParser\v2\Modules\Tools\Tools;

class SoundModel extends Model
{
    public const COMMAND = 'sound';
    public const EXTENSION = '.ogg';

    public string $path;
    public function parse() : self
    {
        $path = $this->line->get(KatawaCore::ARG_SECOND);

        $pos = strpos($path, '_');
        if ($pos !== false) {
            $path = substr_replace($path, '/', $pos, strlen('/'));
        }

        $this->path = $path;
        return parent::parse(); // TODO: Change the autogenerated stub
    }

    public function compile(): string
    {
        return self::COMMAND.' '.Tools::quoted($this->path.self::EXTENSION).' '.'-1';
    }
}
