<?php

namespace Modules\KatawaCore\v2\Modules\GameModel;

use Modules\KatawaCore\v2\KatawaCore;

class WrittenNote extends Model
{
    public const COMMAND = 'note';

    public string $text;

    public bool $html = false;

    public string $blockStart = '<span style=\'font-size: 250%;\'>\n\n';

    public string $blockEnd = '</span>';

    public function parse(): self
    {
        $line = clone $this->line;
        $line->forget(KatawaCore::ARG_COMMAND);
        $line->forget(KatawaCore::ARG_FIRST);

        $this->text = $this->line->get(KatawaCore::ARG_SECOND);

        return parent::parse(); // TODO: Change the autogenerated stub
    }

    public function compile(): string
    {
        if ($this->html) {
            return self::COMMAND.' '.$this->blockStart.$this->text.$this->blockEnd;
        }

        return self::COMMAND.' '.$this->text;
    }

    public function setHtml(bool $html = true): self
    {
        $this->html = $html;

        return $this;
    }
}
